name: Restart server

on: [workflow_dispatch]

jobs:
  restart-server:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: Restart ark-server container with ssh
      uses: appleboy/ssh-action@master
      continue-on-error: true
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ~/games/ark-server
          make restart-server
        
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'The Ark server has been restarted.'
